const fs = require('fs')
const os = require('os')
const path = require('path')

const { PACKAGE_ROOT, megamemHome, homeEnvPath } = require('../src/config/env')

// Global install: register the MCP server once for every project and install
// user-level Cursor hooks so the session briefing and session-end capture fire
// everywhere, not just inside this repo.
//
// Cursor spawns MCP servers with cwd set to the opened project root, and the
// workspace layer is derived from cwd (src/utils/sessionId.js), so a global
// registration still scopes memories per project.
//
// User-level hooks are spawned from ~/.cursor/, which is why the hook scripts
// are thin launchers: requiring the real hook by absolute path keeps its
// __dirname inside the package, so its relative requires keep resolving.

const SERVER_NAME = 'megamem'

const CURSOR_DIR = path.join(os.homedir(), '.cursor')
const MCP_JSON = path.join(CURSOR_DIR, 'mcp.json')
const HOOKS_JSON = path.join(CURSOR_DIR, 'hooks.json')
const HOOKS_DIR = path.join(CURSOR_DIR, 'hooks')
const INSTALL_JSON = path.join(megamemHome(), 'install.json')

const HOOKS = [
  { event: 'sessionStart', launcher: 'megamem-session-start.js', target: '.cursor/hooks/session-start.js', timeout: 20 },
  { event: 'sessionEnd', launcher: 'megamem-session-end.js', target: '.cursor/hooks/session-end.js', timeout: 30 }
]

const mcpServerPath = () => path.join(PACKAGE_ROOT, 'src', 'mcpServer.js')

const readJson = (file, fallback) => {
  if (!fs.existsSync(file)) return { ...fallback }
  const raw = fs.readFileSync(file, 'utf8').trim()
  if (!raw) return { ...fallback }

  let parsed
  try {
    parsed = JSON.parse(raw)
  } catch (error) {
    throw new Error(`Invalid JSON in ${file}: ${error.message}`, { cause: error })
  }
  if (!parsed || typeof parsed !== 'object' || Array.isArray(parsed)) {
    throw new Error(`${file} must contain a JSON object`)
  }
  return parsed
}

const writeJson = (file, value) => {
  fs.mkdirSync(path.dirname(file), { recursive: true })
  fs.writeFileSync(file, JSON.stringify(value, null, 2) + '\n')
}

const isOurHook = (entry) => typeof entry?.command === 'string' && /megamem-session-(start|end)\.js/.test(entry.command)

const launcherSource = (hook) => `#!/usr/bin/env node
// Generated by \`megamem setup\` — do not edit.
// The real hook lives in the installed package; re-run \`megamem setup\`
// if this install is ever moved.
require(${JSON.stringify(path.join(PACKAGE_ROOT, hook.target))})
`

// Seeds ~/.megamem/.env so the install survives the repo being moved or
// deleted. Prefers the repo's filled-in .env when migrating an existing setup.
const ensureHomeEnv = () => {
  const target = homeEnvPath()
  if (fs.existsSync(target)) return { action: 'kept', path: target }

  const repoEnv = path.join(PACKAGE_ROOT, '.env')
  const template = path.join(PACKAGE_ROOT, '.env.example')
  const source = fs.existsSync(repoEnv) ? repoEnv : (fs.existsSync(template) ? template : null)

  fs.mkdirSync(path.dirname(target), { recursive: true })
  fs.writeFileSync(target, source ? fs.readFileSync(source) : '', { mode: 0o600 })

  return { action: source === repoEnv ? 'copied-repo' : 'template', path: target, source }
}

const install = () => {
  const env = ensureHomeEnv()

  fs.mkdirSync(HOOKS_DIR, { recursive: true })
  for (const hook of HOOKS) {
    const launcherPath = path.join(HOOKS_DIR, hook.launcher)
    fs.writeFileSync(launcherPath, launcherSource(hook))
    fs.chmodSync(launcherPath, 0o755)
  }

  const mcp = readJson(MCP_JSON, { mcpServers: {} })
  mcp.mcpServers = mcp.mcpServers && typeof mcp.mcpServers === 'object' ? mcp.mcpServers : {}
  mcp.mcpServers[SERVER_NAME] = { command: process.execPath, args: [mcpServerPath()] }
  writeJson(MCP_JSON, mcp)

  // Merge rather than replace: other tools' user-level hooks must survive.
  const hooksConfig = readJson(HOOKS_JSON, { version: 1, hooks: {} })
  hooksConfig.version = hooksConfig.version || 1
  hooksConfig.hooks = hooksConfig.hooks && typeof hooksConfig.hooks === 'object' ? hooksConfig.hooks : {}

  for (const hook of HOOKS) {
    const existing = Array.isArray(hooksConfig.hooks[hook.event]) ? hooksConfig.hooks[hook.event] : []
    const launcherPath = path.join(HOOKS_DIR, hook.launcher)
    hooksConfig.hooks[hook.event] = [
      ...existing.filter((entry) => !isOurHook(entry)),
      { command: `"${process.execPath}" "${launcherPath}"`, timeout: hook.timeout }
    ]
  }
  writeJson(HOOKS_JSON, hooksConfig)

  writeJson(INSTALL_JSON, {
    packageRoot: PACKAGE_ROOT,
    nodePath: process.execPath,
    installedAt: new Date().toISOString()
  })

  return { env, mcpJson: MCP_JSON, hooksJson: HOOKS_JSON, launchers: HOOKS.map((h) => path.join(HOOKS_DIR, h.launcher)) }
}

const uninstall = ({ purge = false } = {}) => {
  const removed = []

  const mcp = readJson(MCP_JSON, { mcpServers: {} })
  if (mcp.mcpServers && SERVER_NAME in mcp.mcpServers) {
    delete mcp.mcpServers[SERVER_NAME]
    writeJson(MCP_JSON, mcp)
    removed.push(`MCP server "${SERVER_NAME}" from ${MCP_JSON}`)
  }

  if (fs.existsSync(HOOKS_JSON)) {
    const hooksConfig = readJson(HOOKS_JSON, { version: 1, hooks: {} })
    for (const event of Object.keys(hooksConfig.hooks || {})) {
      if (!Array.isArray(hooksConfig.hooks[event])) continue
      hooksConfig.hooks[event] = hooksConfig.hooks[event].filter((entry) => !isOurHook(entry))
      if (hooksConfig.hooks[event].length === 0) delete hooksConfig.hooks[event]
    }

    if (Object.keys(hooksConfig.hooks || {}).length === 0) {
      fs.rmSync(HOOKS_JSON)
      removed.push(`${HOOKS_JSON} (no hooks left)`)
    } else {
      writeJson(HOOKS_JSON, hooksConfig)
      removed.push(`MegaMem hooks from ${HOOKS_JSON}`)
    }
  }

  for (const hook of HOOKS) {
    const launcherPath = path.join(HOOKS_DIR, hook.launcher)
    if (fs.existsSync(launcherPath)) {
      fs.rmSync(launcherPath)
      removed.push(launcherPath)
    }
  }

  if (fs.existsSync(INSTALL_JSON)) {
    fs.rmSync(INSTALL_JSON)
    removed.push(INSTALL_JSON)
  }

  if (purge && fs.existsSync(homeEnvPath())) {
    fs.rmSync(homeEnvPath())
    removed.push(homeEnvPath())
  }

  return removed
}

const readInstallInfo = () => {
  if (!fs.existsSync(INSTALL_JSON)) return null
  try {
    return JSON.parse(fs.readFileSync(INSTALL_JSON, 'utf8'))
  } catch {
    return null
  }
}

module.exports = {
  SERVER_NAME,
  MCP_JSON,
  HOOKS_JSON,
  HOOKS_DIR,
  INSTALL_JSON,
  HOOKS,
  mcpServerPath,
  isOurHook,
  install,
  uninstall,
  readInstallInfo
}
